services:
  confmapper_server:
    container_name: conferencemapper
    image: conferencemapper
    volumes:
      - ./config/config_sample.php:/usr/local/ConferenceMapper/src/policyserver/config/config.php
    ports:
      - "8081:80"
      - "8445:443"
    logging:
      driver: syslog
      options:
        tag: "conferencemapper"
    depends_on:
        my_sql_local:
           condition: service_healthy
    environment:
      DB_PASSWORD: rdv_password
      DB_USER: rdv_user
      DB_HOST: my_sql_local
      JITSI_DOMAIN: rdv43.rendez-vous.renater.fr
      PHONE_NUMBER_LIST: '0978080000'
      JIGASI_EXTANSION_LIST: "'666','555'"
      LIFETIME_SHORT: 6
      LIFETIME_LONG: 1440

  my_sql_local:
    container_name: my_sql_local
    image: mysql:8.0.31
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password4rootroot
      MYSQL_DATABASE: rendezvous
      MYSQL_USER: rdv_user
      MYSQL_PASSWORD: rdv_password
      MAX_ALLOWED_PACKET: 1073741824
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10

volumes:
  mysql-data: